### PR TITLE
Adaptable css

### PR DESCRIPTION
**Pull request by ghost**
Making the portfolio adaptable with media queries

### CODE REVIEW

**Comment by ShoiraTa** [comment]
STATUS: CHANGES REQUIRED 🟡 
----
Hi @iKuartz ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- You passed all the Linters! ✔️ 
- Professional UI and UX! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!



 ## Required Changes  :recycle: 

- [x] Please add pull request description 😉 
- [x] I have noticed that you have committed all the node modules and your project on Github became huge and makes it almost impossible to review the project 😢 
> Please delete node modules from the Github repository (add `node_modules` into `.gitignore` file)

- [x] Did you know that on Figma you are provided with buttons design 😉? I kindly suggest you to add hover effect as provided in Figma:
image

***
Cheers and Happy coding! :clap: :clap: :clap:

**Comment by ghost** [comment]
I committed the node modules to main branch by mistake, but already removed it from this branch. Will remove from main too. Thank you.

**Comment by ghost** [comment]
I did not know Figma provided those button interaction objectives! I will look for them and implement them. Thank you.

**Comment by ghost** [comment]
Buttons are OK now! :)

**Review by Lordkaito — APPROVED** [review]
Hi @iKuartz, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
